version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /apps/api
    target-branch: develop
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /apps/web
    target-branch: develop
    schedule:
      interval: weekly
